version: '3.9'

services:
  database:
    container_name: database
    image: 'postgres:15-alpine'
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '127.0.0.1:${DATABASE_PORT}:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 3s
      
  application:
    build:
      context: .
    container_name: application
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy